server:
  port: 8080

spring:
  # --- Configuración para PostgreSQL (Comandos / JPA) ---
  datasource:
    # ESTA ES LA SOLUCIÓN: Construimos manualmente la URL en el formato correcto
    # usando la variable de entorno que nos da Render.
    url: jdbc:${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # Mantenemos el dialecto explícito como buena práctica y seguro adicional.
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # --- Configuración para MongoDB (Consultas) ---
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}