server:
  port: 8080

spring:
  # --- Configuraci칩n para PostgreSQL (Comandos / JPA) ---
  datasource:
    url: jdbc:postgresql://postgres-db:5432/guias_db_command
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # En desarrollo, crea/actualiza el esquema autom치ticamente. Cambiar a 'validate' o 'none' en producci칩n.
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # --- Configuraci칩n para MongoDB (Consultas) ---
  data:
    mongodb:
      uri: mongodb://user:password@mongo-db:27017/guias_db_query?authSource=admin