server:
  port: 8080

spring:
  # --- Configuración para PostgreSQL (Comandos / JPA) ---
  datasource:
    url: jdbc:${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # --- Configuración para MongoDB (Consultas) ---
  data:
    mongodb:
      # Esta línea también cambia para usar la variable de entorno directamente
      uri: ${SPRING_DATA_MONGODB_URI}