server:
  port: 8080

spring:
  jpa:
    hibernate:
      # Esta opción crea o actualiza las tablas al arrancar. Ideal para desarrollo.
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # LA LÍNEA MÁS IMPORTANTE DE LA SOLUCIÓN:
        # Le decimos explícitamente a Hibernate que estamos usando el dialecto de PostgreSQL.
        # Esto evita que necesite conectarse para adivinarlo.
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # La configuración de MongoDB se queda igual. Spring tomará la variable de entorno.
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}